### ISSUE TITLE
[Recomendation] is_send() tests

### ISSUE THREAD

**Issue by audioXD** [stevepryde/thirtyfour_query#4]
I think there should be some tests for the all the future methods to check if the result is `Send`. To prevent any future breakages.

```
fn is_send<T: Send>() {}
fn is_send_val<T: Send>(val: &T) {}

...

is_send_val(&query.first())
```

**Comment by audioXD** [comment]
Is there a way to do a mock driver/query?

**Comment by stevepryde** [comment]
Have a look at the doctests for `thirtyfour` - I think we could the same for this one

**Comment by stevepryde** [comment]
I've already implemented a similar doctest for `ElementQuery` (similar to `thirtyfour`, not this issue) just as a general sanity check. Eventually every method should be tested in some way.

**Comment by audioXD** [comment]
Nice, thanks! 👍
