### ISSUE TITLE
Version bump required

### ISSUE THREAD

**Issue by TilBlechschmidt** [stevepryde/thirtyfour_query#9]
Hello again 👋 

The recent change in `thirtyfour` which bumped it up to `v0.24.0` requires a bump in the dependency of this crate. Otherwise, nasty problems crop up when using `thirtyfour @ 0.24.0, thirtyfour_query @ 0.6`:
```
error[E0599]: no method named `query` found for mutable reference `&mut GenericWebDriver<ReqwestDriverAsync>` in the current scope
   --> src/main.rs:105:26
    |
105 |     let results = driver.query(By::ClassName("result__a")).all().await?;
    |                          ^^^^^ method not found in `&mut GenericWebDriver<ReqwestDriverAsync>`

warning: unused import: `ElementQueryable`
 --> src/main.rs:4:39
  |
4 | use thirtyfour_query::{ElementPoller, ElementQueryable};
  |                                       ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted
```

**Comment by TilBlechschmidt** [comment]
In general: Is there any solution to this kind of dependency pinning issue on dependent libraries? I know that the NodeJS ecosystem solved it with peer dependencies — haven't come across anything related in the Rust ecosystem 🤔

**Comment by stevepryde** [comment]
In theory it has to be like this because 0.24.0 was a breaking change. I'll have a look at this shortly

**Comment by stevepryde** [comment]
It's probably worth merging this into `thirtyfour` at some stage. The plan was to get the interface stable externally to avoid doing a million version bumps on the main `thirtyfour` project, and then merge it in after that.

**Comment by stevepryde** [comment]
Version `v0.7.0` published now
